version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: web_shop
    volumes:
      - ./storage/src/main/resources/sql/create.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432

  postgres2:
    image: postgres:latest
    restart: always
    container_name: payments
    volumes:
      - ./payment/src/main/resources/sql/create.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5434:5432

  postgres3:
    image: postgres:latest
    restart: always
    container_name: clients
    volumes:
      - ./client/src/main/resources/sql/create.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5435:5432

  keycloak:
    image: "quay.io/keycloak/keycloak:23.0.6"
    container_name: keycloak_serv
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm