server:
  port: 8083

spring:
  application:
    name: storageAdmin
  servlet:
    multipart:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/storage_admin
            user-name-attribute: preferred_username
        registration:
          storage-admins-app-client-credentials:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: storage_app
            client-secret: q3h9h9U0ojyqX3bNrncInEVHaXoExNFo
            scope:
              - storage_admins
          storage-admins-app-authorization-code:
            provider: keycloak
            client-id: storage_app
            client-secret: q3h9h9U0ojyqX3bNrncInEVHaXoExNFo
            scope:
              - storage_admins
              - openid
              - microprofile-jwt


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
