server:
  port: 8083

spring:
  application:
    name: storageAdmin
  servlet:
    multipart:
      enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:18080/realms/sandbox
            user-name-attribute: preferred_username
        registration:
          storage-app-client-credential:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: storage-app
            client-secret: aDrAC2X0SvF450LS6vAR1pZcGRNvDFyM
            scope:
              - greetings
          storage-app-authorization-code:
            provider: keycloak
            client-id: storage-app
            client-secret: aDrAC2X0SvF450LS6vAR1pZcGRNvDFyM
            scope:
              - openid
              - microprofile-jwt


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

image:
  path:
    part: D:\\backup\\4\\Spring_web_shop\\storage\\images
