server:
  port: 8081

spring:
  application:
    name: appPayment
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka