server:
  port: 8082

spring:
  application:
    name: client
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
#app:
#  path:
#    storage: http://localhost:8080/api/v1
#    payment: http://localhost:8081/api/v2

#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus,info,metrics,threaddump,health

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown

image:
  path:
    part: ./client/images

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

integration:
  path: ./client/messages

