server:
  port: 8080

spring:
  application:
    name: appStorage
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
  servlet:
    multipart:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/storage_admin

app:
  image:
    path: ./storage/images

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka